/** Auto-generated by scripts/build-logo-masks.mjs — do not edit by hand. */
export const LOGO_FULL = {
  ink: "/logo-ink-mask.png",
  fold: "/logo-fold-mask.png",
  width: 742,
  height: 636,
} as const;

export const LOGO_ICON = {
  ink: "/logo-ink-mask-icon.png",
  fold: "/logo-fold-mask-icon.png",
  width: 340,
  height: 636,
} as const;
